- Gruntfile.js
Required: https://github.com/agoravoting/agora-gui-common/pull/6
> Changed avConfig version

- avBooth/simultaneous-questions-screen-directive/simultaneous-question-answers-screen-directive.html
- avBooth/simultaneous-questions-screen-directive/simultaneous-question-answers-screen-directive.js
- avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.html
- avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.js
- avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.less
- index.html
Initial commit, with new directive to draw the question answers
> Simultaneous question categories support

- avBooth/simultaneous-question-answer-directive/simultaneous-question-answer-directive.html
- avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.js
- locales/en.json
allow or disallow voting to different groups
> enable panachage

- avBooth/booth-directive/booth-directive.js
- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.html
- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.js
- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.less
- avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.html
- avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.js
- avBooth/success-screen-directive/success-screen-directive.html
- avBooth/success-screen-directive/success-screen-directive.js
- locales/en.json
* applying disable__election_chooser_screen
* fixing disabled calculation
* getting updated election credentials
* using parent election to check the flag
* do not show skipped elections nor voted elections
* fix typo
* allow to skip last election
* showing skipped elections in success screen when voted in all others
* showing logout option in election chooser
* wrong function call
* showing logout button
> Disable election chooser flag

- package.json
- yarn.lock
* updating json-schema
* updating yarn.lock
> Security dependency update: json schema 0.4.0 (#173)

- avBooth/selected-options-filter.js
- avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.js
* fixing review screen count when invalid answer selected
* fix lint
> fixing review screen count when invalid answer selected

- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.js
isFirst should indicate if it's the first token, not the first election in the natural order list.
> fixing isFirst in vote-permission-token processing

- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.js
* hide elections that are not the voter's
* fix calculateIsVoter
> hide elections that are not the voter's

- avBooth/booth-directive/booth-directive.js
- avBooth/success-screen-directive/success-screen-directive.js
- index.html
- package.json
- yarn.lock
Currently the PDF ballot ticket does not include any timezone indicator. Fix that.
> adding timezone to the ballot ticket

- avBooth/2questions-conditional-screen-directive/2questions-conditional-screen-directive.html
- avBooth/conditional-accordion-screen-directive/conditional-accordion-screen-directive.html
- avBooth/help-screen-directive/help-screen-directive.html
- avBooth/multi-question-directive/multi-question-directive.html
- avBooth/pairwise-beta-directive/pairwise-beta-directive.html
- avBooth/pcandidates-election-screen-directive/pcandidates-election-screen-directive.html
- avBooth/review-screen-directive/review-screen-directive.html
- avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.html
- avBooth/start-screen-directive/start-screen-directive.html
6.1.x version of [this PR](https://github.com/sequentech/voting-booth/pull/246)
> Button colors 6

- avBooth/booth-directive/booth-directive.less
[Same PR as this](https://github.com/sequentech/voting-booth/pull/248), but for version 6.
> Fix logo max height

- avBooth/booth.less
- avBooth/encrypting-ballot-screen-directive/encrypting-ballot-screen-directive.html
- avBooth/encrypting-ballot-screen-directive/encrypting-ballot-screen-directive.less
- avBooth/review-ballot-directive/review-ballot-directive.html
- avBooth/review-ballot-directive/review-ballot-directive.less
- avBooth/review-screen-directive/review-screen-directive.less
- avBooth/success-screen-directive/success-screen-directive.html
> More mobile fixes

- avBooth/booth.less
- avBooth/encrypting-ballot-screen-directive/encrypting-ballot-screen-directive.html
- avBooth/encrypting-ballot-screen-directive/encrypting-ballot-screen-directive.less
- avBooth/review-ballot-directive/review-ballot-directive.html
- avBooth/review-ballot-directive/review-ballot-directive.less
- avBooth/review-screen-directive/review-screen-directive.less
- avBooth/success-screen-directive/success-screen-directive.html
[See master PR](https://github.com/sequentech/voting-booth/pull/259)
> More mobile fixes (#259)

- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.js
Include changes from [this PR](https://github.com/sequentech/voting-booth/pull/265) in the 7.0.x release
> Add org details to election chooser directive 

- avBooth/accordion-option-directive/accordion-option-directive.less
- avBooth/conditional-accordion-screen-directive/conditional-accordion-screen-directive.html
- avBooth/multi-question-directive/multi-question-directive.html
- avBooth/pcandidates-election-screen-directive/pcandidates-election-screen-directive.html
* Fix `links` on accordion options.
* Fix input labels  on conditional accordion, multi-question, pcandidates.
> Accessibility fixes for accordion layout

- avBooth/accordion-option-directive/accordion-option-directive.less
- avBooth/conditional-accordion-screen-directive/conditional-accordion-screen-directive.html
- avBooth/multi-question-directive/multi-question-directive.html
- avBooth/pcandidates-election-screen-directive/pcandidates-election-screen-directive.html
* Fix `links` on accordion options.
* Fix input labels  on conditional accordion, multi-question, pcandidates.
> Accessibility fixes for accordion layout 

- avBooth/simultaneous-question-answer-directive/simultaneous-question-answer-directive.html
- avBooth/simultaneous-question-answer-directive/simultaneous-question-answer-directive.js
- avBooth/simultaneous-question-answer-directive/simultaneous-question-answer-directive.less
- avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.html
- avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.js
* adding extended support for rigid, open and loosely bound lists
* WIP
* WIP
* WIP
* WIP
---------
Co-authored-by: Félix Robles <felix@sequentech.io>
> Adding extended support for rigid, open and loosely bound lists

- avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.js
* ui improvements
* also soft
---------
> Warn implicit and explicit votes fix (#299)

- Gruntfile.js
- avBooth/booth-header-directive/booth-header-directive.html
- locales/fr.json
Parent issue: https://github.com/sequentech/meta/issues/48
> French language support

- Gruntfile.js
- index.html
Parent issue: https://github.com/sequentech/meta/issues/68
> favicon.ico not loading

- Gruntfile.js
- index.html
Parent issue: https://github.com/sequentech/meta/issues/68
> favicon.ico not loading (#319)

- avBooth/success-screen-directive/success-screen-directive.js
Parent issue: https://github.com/sequentech/meta/issues/93
> Incorrect message about skipped ballots

- avBooth/booth-directive/booth-directive.less
Parent issue: https://github.com/sequentech/meta/issues/112
> ✨ Shrink header/footer by default (#330)

- locales/ca.json
- locales/es.json
- locales/gl.json
Parent Issue: https://github.com/sequentech/meta/issues/130
> 🐞French translation is tagged as English

- locales/ca.json
- locales/es.json
- locales/gl.json
Parent Issue: https://github.com/sequentech/meta/issues/130
> 🐞French translation is tagged as English (#335)

- avBooth/review-ballot-v2-directive/review-ballot-v2-directive.html
- avBooth/simultaneous-questions-v2-screen-directive/simultaneous-questions-v2-screen-directive.html
- avBooth/simultaneous-questions-v2-screen-directive/simultaneous-questions-v2-screen-directive.js
Parent Issue: https://github.com/sequentech/epi/issues/119
> ✨dynamic position of invalid vote option

- avBooth/review-ballot-v2-directive/review-ballot-v2-directive.html
- avBooth/simultaneous-questions-v2-screen-directive/simultaneous-questions-v2-screen-directive.html
- avBooth/simultaneous-questions-v2-screen-directive/simultaneous-questions-v2-screen-directive.js
Parent Issue: https://github.com/sequentech/epi/issues/119
> ✨dynamic position of invalid vote option (#336)

- Gruntfile.js
- SequentConfig.js
- index.html
- package.json
Parent issue: https://github.com/sequentech/meta/issues/136
This reverts commit cfbdf5698662bce5431867c8f5ecbdbd6ecab6fc.
> `master` branch should be using `master` version number and not `8.0.0`

- package.json
- yarn.lock
Parent issue: https://github.com/sequentech/meta/issues/135
> Security updates: word-wrap resolution

- package.json
- yarn.lock
Parent issue: https://github.com/sequentech/meta/issues/135
> Security updates: word-wrap resolution (#343)

- avBooth/error-checker-generator-service.js
- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.html
- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.js
- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.less
- locales/ca.json
- locales/en.json
- locales/es.json
- locales/fi.json
- locales/fr.json
- locales/gl.json
- locales/sv.json
Parent issue: https://github.com/sequentech/meta/issues/125
> ✨ Write-ins multiple fields

- avBooth/booth-directive/booth-directive.js
Parent issue: https://github.com/sequentech/voting-booth/issues/321
> 🐞 dynamic translation issues

- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.html
Parent issue: https://github.com/sequentech/meta/issues/150
> ✨ Add html support for write-in extrafield labels/help

- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.less
Parent issue: https://github.com/sequentech/meta/issues/145
> 🐞The booth shows the write-in character count twice, and in an odd place

- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.less
Parent issue: https://github.com/sequentech/meta/issues/145
> 🐞The booth shows the write-in character count twice, and in an odd place (#351)

- avBooth/simultaneous-questions-category-v2-directive/simultaneous-questions-category-v2-directive.html
Parent issue: https://github.com/sequentech/meta/issues/139
> 🐞 rigid lists: candidates check boxes should not be shown

- avBooth/simultaneous-questions-category-v2-directive/simultaneous-questions-category-v2-directive.html
Parent issue: https://github.com/sequentech/meta/issues/139
> 🐞 rigid lists: candidates check boxes should not be shown (#348)

- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.js
Parent issue: https://github.com/sequentech/meta/issues/138
> 🐞 disable election chooser doesn't work in preview

- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.js
Parent issue: https://github.com/sequentech/meta/issues/138
> 🐞 disable election chooser doesn't work in preview (#347)

- avBooth/simultaneous-questions-category-v2-directive/simultaneous-questions-category-v2-directive.html
- avBooth/simultaneous-questions-category-v2-directive/simultaneous-questions-category-v2-directive.less
- avBooth/simultaneous-questions-v2-screen-directive/simultaneous-questions-v2-screen-directive.html
- avBooth/simultaneous-questions-v2-screen-directive/simultaneous-questions-v2-screen-directive.js
Parent issue: https://github.com/sequentech/meta/issues/148
> 🐞 The candidates would not be displayed if write ins active

- avBooth/simultaneous-questions-category-v2-directive/simultaneous-questions-category-v2-directive.html
- avBooth/simultaneous-questions-category-v2-directive/simultaneous-questions-category-v2-directive.less
- avBooth/simultaneous-questions-v2-screen-directive/simultaneous-questions-v2-screen-directive.html
- avBooth/simultaneous-questions-v2-screen-directive/simultaneous-questions-v2-screen-directive.js
Parent issue: https://github.com/sequentech/meta/issues/148
---------
> 🐞 The candidates would not be displayed if write ins active (#357)

- avBooth/simultaneous-questions-v2-screen-directive/simultaneous-questions-v2-screen-directive.js
Parent issue: https://github.com/sequentech/meta/issues/183
> 🐞 Voting booth doesn't shuffle answers

- avBooth/booth-children-elections-directive/booth-children-elections-directive.html
- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.js
Parent issue: https://github.com/sequentech/meta/issues/212
> Fix: voted elections still active in election chooser

- avBooth/booth-children-elections-directive/booth-children-elections-directive.html
- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.js
Parent issue: https://github.com/sequentech/meta/issues/212
> Fix: voted elections still active in election chooser (#373)

- avBooth/booth-directive/booth-directive.less
- avBooth/simultaneous-questions-v2-screen-directive/simultaneous-questions-v2-screen-directive.html
- avBooth/simultaneous-questions-v2-screen-directive/simultaneous-questions-v2-screen-directive.less
Parent issue: https://github.com/sequentech/meta/issues/223
> Answer column size not applied when not using categories (#366)

- avBooth/booth-children-elections-directive/booth-children-elections-directive.html
- avBooth/booth-children-elections-directive/booth-children-elections-directive.js
- avBooth/booth-children-elections-directive/booth-children-elections-directive.less
- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.html
- avBooth/success-screen-directive/success-screen-directive.js
Parent issue: https://github.com/sequentech/meta/issues/213
> 🐞 public page is active

- avBooth/booth-children-elections-directive/booth-children-elections-directive.less
Parent issue: https://github.com/sequentech/meta/issues/220
> 🐞 child election with bigger title in election chooser

- avBooth/booth-children-elections-directive/booth-children-elections-directive.less
Parent issue: https://github.com/sequentech/meta/issues/220
> 🐞 child election with bigger title in election chooser (#370)

- avBooth/booth-directive/booth-directive.less
Parent issue: https://github.com/sequentech/meta/issues/210
> 🐞 pop up election-id to long

- index.html
- package.json
- yarn.lock
Parent issue: https://github.com/sequentech/meta/issues/230
> Security updates

- avBooth/booth-children-elections-directive/booth-children-elections-directive.less
Parent issue: https://github.com/sequentech/meta/issues/220
> 🐞 child election with bigger title in election chooser (#382)

- app.js
- avBooth/accordion-option-directive/accordion-option-directive.js
- avBooth/is-service.js
- avBooth/selected-options-directive/selected-options-directive.js
- index.html
Parent issue: https://github.com/sequentech/meta/issues/233
> 🐞 Accordion doesn't work as is-js is not loaded

- app.js
- avBooth/accordion-option-directive/accordion-option-directive.js
- avBooth/is-service.js
- avBooth/selected-options-directive/selected-options-directive.js
- index.html
Parent issue: https://github.com/sequentech/meta/issues/233
> 🐞 Accordion doesn't work as is-js is not loaded (#384)

- avBooth/error-checker-generator-service.js
- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.html
- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.js
- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.less
- locales/ca.json
- locales/en.json
- locales/es.json
- locales/fi.json
- locales/fr.json
- locales/gl.json
- locales/sv.json
Parent issue: https://github.com/sequentech/meta/issues/125
> ✨ Write-ins multiple fields (#350)

- avBooth/review-ballot-v2-directive/review-ballot-v2-directive.html
- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.html
- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.js
- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.less
Parent issue: https://github.com/sequentech/meta/issues/151
> ✨ Visualization of write-in fields in Review (#363)

- Gruntfile.js
- locales/it.json
Parent issue: https://github.com/sequentech/meta/issues/235
> Add italian language support

- avBooth/success-screen-directive/success-screen-directive.js
Parent issue: https://github.com/sequentech/epi/issues/112
> ✨ Voting-booth: Improve election info in the ballot ticket PDF for parent-children elections

- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.js
Parent issue: https://github.com/sequentech/meta/issues/264
> 🐞disable election chooser option is not working

- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.js
Parent issue: https://github.com/sequentech/meta/issues/264
> 🐞disable election chooser option is not working (#393)

- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.html
Parent issue: https://github.com/sequentech/meta/issues/263
> 🐞 Selection state of a write-ins answer should not be changed when inputting with space key in the input type text

- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.html
Parent issue: https://github.com/sequentech/meta/issues/263
> 🐞 Selection state of a write-ins answer should not be changed when inputting with space key in the input type text (#396)

- avBooth/error-checker-generator-service.js
- avBooth/success-screen-directive/success-screen-directive.js
Parent issue: https://github.com/sequentech/meta/issues/268
> 🐞 election-title_i18n is not applied everywhere

- avBooth/error-checker-generator-service.js
- avBooth/success-screen-directive/success-screen-directive.js
Parent issue: https://github.com/sequentech/meta/issues/268
> 🐞 election-title_i18n is not applied everywhere (#401)

- package.json
- yarn.lock
Parent issue: https://github.com/sequentech/meta/issues/279
> Security updates (#403)

- avBooth/booth-directive/booth-directive.js
- avBooth/success-screen-directive/success-screen-directive.js
Parent issue: https://github.com/sequentech/meta/issues/282
> 🐞 500 after vote has been casted

- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.js
Parent issue: https://github.com/sequentech/meta/issues/290
> 🐞 Parent-children elections always request all children, even if voter can only vote in one

- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.js
Parent issue: https://github.com/sequentech/meta/issues/290
> 🐞 Parent-children elections always request all children, even if voter can only vote in one (#407)

- avBooth/booth-directive/booth-directive.less
- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.less
- avBooth/simultaneous-questions-category-v2-directive/simultaneous-questions-category-v2-directive.less
Parent issue: https://github.com/sequentech/meta/issues/276
> 🐞 List layout issues

- avBooth/booth-directive/booth-directive.less
- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.less
- avBooth/simultaneous-questions-category-v2-directive/simultaneous-questions-category-v2-directive.less
Parent issue: https://github.com/sequentech/meta/issues/276
> 🐞 List layout issues (#409)

- package.json
- yarn.lock
Parent issue: https://github.com/sequentech/meta/issues/339
> 🛡 Security updates (#414)

- avBooth/booth-directive/booth-directive.js
Parent issue: https://github.com/sequentech/meta/issues/306
> ✨ Select languages per election

- avBooth/booth-directive/booth-directive.js
Parent issue: https://github.com/sequentech/meta/issues/306
> ✨ Select languages per election (#413)

- avBooth/start-screen-directive/start-screen-directive.html
- avBooth/start-screen-directive/start-screen-directive.js
- avBooth/start-screen-directive/start-screen-directive.less
Parent issue: https://github.com/sequentech/meta/issues/224
> ✨ Security confirmation

- avBooth/start-screen-directive/start-screen-directive.html
- avBooth/start-screen-directive/start-screen-directive.js
- avBooth/start-screen-directive/start-screen-directive.less
Parent issue: https://github.com/sequentech/meta/issues/224
> ✨ Security confirmation (#411)

- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.html
- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.js
- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.less
> 🐞 Responsive wraps for high cumulative votes

- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.html
- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.js
- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.less
> 🐞 Responsive wraps for high cumulative votes (#412)

- avBooth/audit-ballot-screen-directive/audit-ballot-screen-directive.html
- avBooth/review-screen-directive/review-screen-directive.html
Parent issue: https://github.com/sequentech/meta/issues/311
> 🐞 title layout on review page (#419)

- app.js
- avBooth/booth-directive/booth-directive.js
Parent issue: https://github.com/sequentech/meta/issues/315
> 🐞 default translation appears when switching language for the first time

- app.js
- avBooth/booth-directive/booth-directive.js
Parent issue: https://github.com/sequentech/meta/issues/315
> 🐞 default translation appears when switching language for the first time (#421)

- app.js
- avBooth/casting-ballot-screen-directive/casting-ballot-screen-directive.js
- avBooth/encrypting-ballot-screen-directive/encrypting-ballot-screen-directive.js
- avBooth/review-ballot-directive/review-ballot-directive.js
- avBooth/review-ballot-v2-directive/review-ballot-v2-directive.js
- avBooth/success-screen-directive/success-screen-directive.js
Parent issue: https://github.com/sequentech/meta/issues/315
> 🐞 default translation appears when switching language for the first time (#425)

- package.json
Parent issue: sequentech/meta#567
Dependabot tickets:
- https://github.com/sequentech/voting-booth/security/dependabot/37
> Security dependencies update

- avBooth/audit-ballot-screen-directive/audit-ballot-screen-directive.html
- avBooth/booth-children-elections-directive/booth-children-elections-directive.html
- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.html
- avBooth/encrypting-ballot-screen-directive/encrypting-ballot-screen-directive.html
- avBooth/review-ballot-v2-directive/review-ballot-v2-directive.html
- avBooth/review-screen-directive/review-screen-directive.html
- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.html
- avBooth/simultaneous-questions-category-v2-directive/simultaneous-questions-category-v2-directive.html
- avBooth/simultaneous-questions-v2-screen-directive/simultaneous-questions-v2-screen-directive.html
- avBooth/start-screen-directive/start-screen-directive.html
- avBooth/success-screen-directive/success-screen-directive.html
- index.html
- locales/ca.json
- locales/en.json
- locales/es.json
Parent issue: https://github.com/sequentech/meta/issues/550
> ✨ Fix WCAG Issues and create new report

- avBooth/audit-ballot-screen-directive/audit-ballot-screen-directive.html
- avBooth/booth-children-elections-directive/booth-children-elections-directive.html
- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.html
- avBooth/encrypting-ballot-screen-directive/encrypting-ballot-screen-directive.html
- avBooth/review-ballot-v2-directive/review-ballot-v2-directive.html
- avBooth/review-screen-directive/review-screen-directive.html
- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.html
- avBooth/simultaneous-questions-category-v2-directive/simultaneous-questions-category-v2-directive.html
- avBooth/simultaneous-questions-v2-screen-directive/simultaneous-questions-v2-screen-directive.html
- avBooth/start-screen-directive/start-screen-directive.html
- avBooth/success-screen-directive/success-screen-directive.html
- index.html
- locales/ca.json
- locales/en.json
- locales/es.json
Parent issue: https://github.com/sequentech/meta/issues/550
> ✨ Fix WCAG Issues and create new report (#427)

- avBooth/error-checker-generator-service.js
- avBooth/invalid-answers-controller/invalid-answers-controller.html
- avBooth/review-ballot-v2-directive/review-ballot-v2-directive.html
- avBooth/review-ballot-v2-directive/review-ballot-v2-directive.js
- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.html
- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.less
- avBooth/simultaneous-questions-category-v2-directive/simultaneous-questions-category-v2-directive.html
- avBooth/simultaneous-questions-v2-screen-directive/simultaneous-questions-v2-screen-directive.html
- avBooth/simultaneous-questions-v2-screen-directive/simultaneous-questions-v2-screen-directive.js
Parent issue: https://github.com/sequentech/meta/issues/678
> 🐞 question-extra-invalid_vote_policy doesn't work

- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.html
Parent issue: https://github.com/sequentech/meta/issues/706
> ✨ Enable selecting blank answers

- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.html
Parent issue: https://github.com/sequentech/meta/issues/706
> ✨ Enable selecting blank answers (#434)

- avBooth/booth-directive/booth-directive.js
- avBooth/error-checker-generator-service.js
Parent issue: https://github.com/sequentech/meta/issues/711
> 🐞 Invalid vote policy

- avBooth/booth-directive/booth-directive.js
- avBooth/error-checker-generator-service.js
Parent issue: https://github.com/sequentech/meta/issues/711
> 🐞 Invalid vote policy (#436)

- avBooth/review-ballot-v2-directive/review-ballot-v2-directive.html
- avBooth/review-ballot-v2-directive/review-ballot-v2-directive.js
Parent issue: https://github.com/sequentech/meta/issues/809
> 🐞 Warning characters rendered incorrectly in review screen (#438)

- avBooth/simultaneous-questions-v2-screen-directive/simultaneous-questions-v2-screen-directive.js
Parent issue: https://github.com/sequentech/meta/issues/911
> 🐞 Double click is needed to deselect

- avBooth/simultaneous-questions-v2-screen-directive/simultaneous-questions-v2-screen-directive.js
Parent issue: https://github.com/sequentech/meta/issues/911
> 🐞 Double click is needed to deselect (#442)

- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.html
Parent issue: https://github.com/sequentech/meta/issues/1058
> 🐞 Link on blank vote

- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.html
Parent issue: https://github.com/sequentech/meta/issues/1058
> 🐞 Link on blank vote (#446)

- avBooth/success-screen-directive/success-screen-directive.js
Parent issue: https://github.com/sequentech/meta/issues/751
> 🐞 date in frontend should be formatted according to browser settings

- avBooth/success-screen-directive/success-screen-directive.js
Parent issue: https://github.com/sequentech/meta/issues/751
> 🐞 date in frontend should be formatted according to browser settings(#448)

- app.js
- avBooth/booth-directive/booth-directive.js
- avBooth/booth.html
- avBooth/booth.js
Parent issue: https://github.com/sequentech/meta/issues/752
> ✨🐞 Improve/rethink/fix Live Preview

- avBooth/booth-directive/booth-directive.js
Parent issue: https://github.com/sequentech/meta/issues/205
> ✨ Increase the timeout due to user activity

- avBooth/booth-directive/booth-directive.js
Parent issue: https://github.com/sequentech/meta/issues/762
> ✨ Separation of voting session time and bearer token lifetime

- avBooth/booth-directive/booth-directive.js
Parent issue: https://github.com/sequentech/meta/issues/1654
> 🐞 400 error after voting

- avBooth/error-checker-generator-service.js
- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.html
Parent issue: https://github.com/sequentech/meta/issues/1670
> 🐞 Write-in issues

- avBooth/error-checker-generator-service.js
- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.html
Parent issue: https://github.com/sequentech/meta/issues/1670
> 🐞 Write-in issues (#459)

- avBooth/booth-directive/booth-directive.js
Parent issue: https://github.com/sequentech/meta/issues/762
> ✨ Separation of voting session time and bearer token lifetime 

- avBooth/booth-directive/booth-directive.js
Parent issue: https://github.com/sequentech/meta/issues/1832
> 🐞 Login error for voters

- avBooth/booth-directive/booth-directive.js
Parent issue: https://github.com/sequentech/meta/issues/1832
> 🐞 Login error for voters (#465)

- avBooth/booth-directive/booth-directive.js
Parent issue: https://github.com/sequentech/meta/issues/1832
> 🐞 Login error for voters (#468)

- avBooth/review-ballot-v2-directive/review-ballot-v2-directive.html
- avBooth/simultaneous-questions-v2-screen-directive/simultaneous-questions-v2-screen-directive.html
Parent issue: https://github.com/sequentech/meta/issues/2572
> ✨ Add field to insert html after a question in the voting/review screens

- avBooth/booth-directive/booth-directive.js
- avBooth/success-screen-directive/success-screen-directive.js
Parent issue: https://github.com/sequentech/meta/issues/1016
> 🐞 Logo displayed incorrectly

- avBooth/booth-directive/booth-directive.js
- avBooth/success-screen-directive/success-screen-directive.js
Parent issue: https://github.com/sequentech/meta/issues/1016
> 🐞 Logo displayed incorrectly (#473)
