sequentech/voting-booth

- avBooth/success-screen-directive/success-screen-directive.html
fix ballot locator link in booth success page, it was using the old link format that is not working anymor
Steps to reproduce the bug:
1. vote (using demo voting booth for example)
2. in the last step, click on the link to find your ballot locator
3. it doesn't work
How it should work instead:
1. vote (using demo voting booth for example)
2. in the last step, click on the link to find your ballot locator
3. page would load the ballot locator
> fix ballot locator link in booth success page

- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.js
Election chooser will be shown always because we are not using credentials in the demo booth so we don't know which election should be shown to the voter.
> fixing demo booth for disabled election chooser

- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.html
- avBooth/start-screen-directive/start-screen-directive.html
If election description was empty in the parent election, the election description of children election would appear and that should not happen.
> Fix election description in parent-elections

- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.html
Log out button in success page (when the voter has finished voting) for parent-children elections should redirect to `election.presentation.extra_options.success_screen__redirect__url` if it that extra option is set. Before, it was ignoring this setting and always redirecting to login after clicking the log-out button.
> Fix log-out button in success screen

- avBooth/success-screen-directive/success-screen-directive.html
When setting not only `success_screen__redirect__url`but also the `success_screen__redirect_to_login`, that activates another button redirect-to-login button different to the default one, to show a specific text that is provided using the `success_screen__redirect_to_login__text` option. In this secondary button, the `success_screen__redirect__url` extra option was being ignored even if provided. This PR fixes that, so that it won't be ignored anymore, and instead, it'll be used for redirecting to the given login url (if provided) in redirect-to-login button in election success screen.
> fix redirect to login button

- avBooth/success-screen-directive/success-screen-directive.html
- avBooth/success-screen-directive/success-screen-directive.js
The activation of the `election.presentation.extra_options.success_screen__hide_ballot_tracker` setting should not hide the Download Ballot ticket button in the voting booth success-screen, but it was doing that so we are fixing it. 
This setting, when enabled, it also hiding the QR Code both in the success screen and within the PDF ballot ticket, so we are fixing that too. Finally, when enabled, this setting should (but it was not) hide the ballot tracker line in the PDF ballot ticket.
> success-screen: Fixing success_screen__hide_ballot_tracker and success_screen__hide_qr_code options

- avBooth/success-screen-directive/success-screen-directive.html
- avBooth/success-screen-directive/success-screen-directive.js
The activation of the `election.presentation.extra_options.success_screen__hide_ballot_tracker` setting should not hide the Download Ballot ticket button in the voting booth success-screen, but it was doing that so we are fixing it. 
This setting, when enabled, it also hiding the QR Code both in the success screen and within the PDF ballot ticket, so we are fixing that too. Finally, when enabled, this setting should (but it was not) hide the ballot tracker line in the PDF ballot ticket.
> success-screen: Fixing success_screen__hide_ballot_tracker and success_screen__hide_qr_code options 

- package.json
- yarn.lock
* Bump follow-redirects from 1.14.0 to 1.14.8
Bumps [follow-redirects](https://github.com/follow-redirects/follow-redirects) from 1.14.0 to 1.14.8.
- [Release notes](https://github.com/follow-redirects/follow-redirects/releases)
- [Commits](https://github.com/follow-redirects/follow-redirects/compare/v1.14.0...v1.14.8)
---
updated-dependencies:
- dependency-name: follow-redirects
dependency-type: indirect
...
Signed-off-by: dependabot[bot] <support@github.com>
* Bump karma from 4.4.1 to 6.3.14
Bumps [karma](https://github.com/karma-runner/karma) from 4.4.1 to 6.3.14.
- [Release notes](https://github.com/karma-runner/karma/releases)
- [Changelog](https://github.com/karma-runner/karma/blob/master/CHANGELOG.md)
- [Commits](https://github.com/karma-runner/karma/compare/v4.4.1...v6.3.14)
--- …
> Fix security issues by updating dependencies

- avBooth/booth-header-directive/booth-header-directive.html
When the election is configured with a logo, the booth header
was not showing neither the version of software nor the log out
button. This commit fixes that.
> Fix booth header when logo_url is set

- avBooth/review-ballot-directive/review-ballot-directive.html
If a vote has been marked as invalid explicitly, it cannot be blank
because it has already one mark. So we don't show the blank vote
mark.
> Fix invalid & blank vote in review screen

- app.less
- avBooth/accordion-option-directive/accordion-option-directive.html
- avBooth/accordion-option-directive/accordion-option-directive.less
- avBooth/booth-header-directive/booth-header-directive.html
- avBooth/booth.less
- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.html
- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.less
- avBooth/multi-question-directive/multi-question-directive.html
- avBooth/multi-question-directive/multi-question-directive.less
- avBooth/review-ballot-directive/review-ballot-directive.html
- avBooth/review-ballot-directive/review-ballot-directive.less
- avBooth/review-screen-directive/review-screen-directive.html
- avBooth/review-screen-directive/review-screen-directive.less
- avBooth/simultaneous-question-answer-directive/simultaneous-question-answer-directive.less
- avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.html
- avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.less
- avBooth/start-screen-directive/start-screen-directive.html
- avBooth/start-screen-directive/start-screen-directive.less
- avBooth/success-screen-directive/success-screen-directive.html
- avBooth/success-screen-directive/success-screen-directive.less
- Ensure that buttons text don't overflow
- Ensure that user-provided text (election/question title, description,
answers..) use `word-break: break-word` css setting to break the words
in two if required because overflowing.
- Ensure that the warning messages in the affix-bottom during ballot
selection doesn't prevent the next button to show nor they take too
much space, by adding `overflow-y: scroll` to that section.
> Fixes for responsible mobile design

- avBooth/booth-directive/booth-directive.js
Graceful voting period allows voters that are already logged in the voting booth to vote even if the election voting period
has ended.
However, this feature didn't work before this bugfix with parent-children elections, because the voting booth ensured that
the election needs to be within the voting period when retrieving the election from the backend, and this retrival happens for each of the children election on demand. When that check did not checkout, the voter would get an error message stating that the election is not started.
This commit fixes the issue by allowing the election to be stopped if the graceful voting period is enabled.
> Fix graceful voting period for parent-child elections

- avBooth/2questions-conditional-screen-directive/2questions-conditional-screen-directive.html
- avBooth/conditional-accordion-screen-directive/conditional-accordion-screen-directive.html
- avBooth/help-screen-directive/help-screen-directive.html
- avBooth/multi-question-directive/multi-question-directive.html
- avBooth/pairwise-beta-directive/pairwise-beta-directive.html
- avBooth/pcandidates-election-screen-directive/pcandidates-election-screen-directive.html
- avBooth/review-screen-directive/review-screen-directive.html
- avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.html
- avBooth/start-screen-directive/start-screen-directive.html
There should be a single call to action on each screen. Normal buttons will be gray, and the CTA will be green.
* Revert the colors of the class `btn-success`to gray.
* Add a new class `btn-success-action` with the green color.
* Use it in the login screens.
This branch is being used at https://felix-dev.sequentech.io
> Button colors

- avBooth/booth-directive/booth-directive.less
The css for the logo at the top left is too large, this fixes it.
Before
After
> Fix logo max height

- avBooth/booth-directive/booth-directive.js
Changing the code so that start screen always shows in the first
election the voter enters, no matter which one is it.
> Fix start screen skipping

- avBooth/booth-directive/booth-directive.js
- avBooth/booth-header-directive/booth-header-directive.html
- avBooth/booth.js
- avBooth/casting-ballot-screen-directive/casting-ballot-screen-directive.js
Now only the documented smart-link authentication option will be
supported. This means that the old smart-link that does not require
any integration with the iam is being removed, to be able to use
iframe integration in the new smart-link authentication method.
> Removing old smart-link iframe authentication method

- app.less
- avBooth/booth-directive/booth-directive.html
- avBooth/booth-directive/booth-directive.js
- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.js
- avBooth/show-pdf-directive/show-pdf-directive.html
- avBooth/show-pdf-directive/show-pdf-directive.js
- avBooth/show-pdf-directive/show-pdf-directive.less
- index.html
- locales/ca.json
- locales/en.json
- locales/es.json
- locales/gl.json
* Add new screen to show PDF.
* Change booth directive to load the screen after login in.
* Add some translations.
Previous PR: https://github.com/sequentech/voting-booth/pull/267
Collapsed PDF (PC):
Expanded PDF (PC):
Collapsed PDF (Mobile):
Expanded PDF (Mobile):
> Support showing PDF in start-screen

- yarn.lock
[Merge features into 7.1.x](https://github.com/sequentech/voting-booth/pull/273)
> Bump socket.io-parser from 4.0.4 to 4.0.5

- yarn.lock
[Merge features into 6.1.x](https://github.com/sequentech/voting-booth/pull/273)
> Bump socket.io-parser from 4.0.4 to 4.0.5 (#273)

- avBooth/success-screen-directive/success-screen-directive.js
When `election.presentation.extra_options.success_screen__hide_qr_code` is set `true`, the ballot confirmation pdf shows a link to the ballot tracker but the link didn't work. This fixes https://github.com/sequentech/roadmap/issues/40
> Bugfix: Link to ballot tracker not working

- app.js
- avBooth/booth-directive/booth-directive.js
- avBooth/booth-header-directive/booth-header-directive.html
- avBooth/booth.html
- avBooth/booth.js
- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.js
- locales/en.json
- locales/es.json
The `Live Preview`feature allows election admins to see the voting booth before creating the election. For the voting booth, this means the election data is not received from the backend server but either through the URL or the session storage.
* Add a new state for the preview election url: `'/:id/preview-vote`.
* Read the election data either from the query param `` or the session storage key `:id` (same id as in the URL).
* The format of the election data is the same as the [Election Creation JSON.](https://sequentech.github.io/documentation/docs/general/reference/election-creation-json/).
* The preview vote screen shows a banner and a modal warning that the ballot won't be cast. Spanish and English translations included.
> Live preview

- app.js
- avBooth/booth-directive/booth-directive.js
- avBooth/booth-header-directive/booth-header-directive.html
- avBooth/booth.html
- avBooth/booth.js
- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.js
- locales/en.json
- locales/es.json
The `Live Preview`feature allows election admins to see the voting booth before creating the election. For the voting booth, this means the election data is not received from the backend server but either through the URL or the session storage.
* Add a new state for the preview election url: `'/:id/preview-vote`.
* Read the election data either from the query param `` or the session storage key `:id` (same id as in the URL).
* The format of the election data is the same as the [Election Creation JSON.](https://sequentech.github.io/documentation/docs/general/reference/election-creation-json/).
* The preview vote screen shows a banner and a modal warning that the ballot won't be cast. Spanish and English translations included.
> Live preview (#284)

- avBooth/booth-directive/booth-directive.js
- avBooth/booth-header-directive/booth-header-directive.html
- avBooth/booth.less
- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.html
- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.less
- avBooth/encrypting-ballot-screen-directive/encrypting-ballot-screen-directive.html
- avBooth/encrypting-ballot-screen-directive/encrypting-ballot-screen-directive.js
- avBooth/invalid-answers-controller/invalid-answers-controller.html
- avBooth/pairwise-beta-directive/pairwise-beta-directive.html
- avBooth/review-ballot-directive/review-ballot-directive.html
- avBooth/review-ballot-directive/review-ballot-directive.js
- avBooth/review-ballot-directive/review-ballot-directive.less
- avBooth/simultaneous-question-answer-directive/simultaneous-question-answer-directive.html
- avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.html
- avBooth/success-screen-directive/success-screen-directive.html
- locales/en.json
- locales/es.json
* Don't logout after 10 mins on demo/live.
* Show a warning modal before the session expires.
* Fix alt text for logo.
* Fix contrast for text warning javascript is off.
* Fix skipped headers on election chooser.
* Improve accessibility on encrypting screen, aria hide changing images, set better description for header.
* Set tabindex to 0 (instead of > 0) on modals' buttons.
* Don't use a header on review ballot when it just contains an aria-hidden icon.
* Add a description for the edit action on review ballot.
* Add alert role to warnings on simultaneous questions screen.
* Better labels for checks (normal, invalid, write-in) on simultaneous questions screen.
* Disable tab for answer container on simultaneous questions screen. Users should only be able to use tab to go through …
> Fx tab/accessibility issues

- avBooth/booth-directive/booth-directive.js
- avBooth/booth-header-directive/booth-header-directive.html
- avBooth/booth.less
- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.html
- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.less
- avBooth/encrypting-ballot-screen-directive/encrypting-ballot-screen-directive.html
- avBooth/encrypting-ballot-screen-directive/encrypting-ballot-screen-directive.js
- avBooth/invalid-answers-controller/invalid-answers-controller.html
- avBooth/pairwise-beta-directive/pairwise-beta-directive.html
- avBooth/review-ballot-directive/review-ballot-directive.html
- avBooth/review-ballot-directive/review-ballot-directive.js
- avBooth/review-ballot-directive/review-ballot-directive.less
- avBooth/simultaneous-question-answer-directive/simultaneous-question-answer-directive.html
- avBooth/simultaneous-question-answer-directive/simultaneous-question-answer-directive.less
- avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.html
- avBooth/success-screen-directive/success-screen-directive.html
- locales/en.json
- locales/es.json
* Don't logout after 10 mins on demo/live.
* Show a warning modal before the session expires.
* Fix alt text for logo.
* Fix contrast for text warning javascript is off.
* Fix skipped headers on election chooser.
* Improve accessibility on encrypting screen, aria hide changing images, set better description for header.
* Set tabindex to 0 (instead of > 0) on modals' buttons.
* Don't use a header on review ballot when it just contains an aria-hidden icon.
* Add a description for the edit action on review ballot.
* Add alert role to warnings on simultaneous questions screen.
* Better labels for checks (normal, invalid, write-in) on simultaneous questions screen.
* Disable tab for answer container on simultaneous questions screen. Users should only be able to use tab to go through …
> Fix tab/accessibility issues

- avBooth/accordion-option-directive/accordion-option-directive.less
- avBooth/booth-directive/booth-directive.js
- avBooth/booth-header-directive/booth-header-directive.html
- avBooth/booth.less
- avBooth/conditional-accordion-screen-directive/conditional-accordion-screen-directive.html
- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.html
- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.less
- avBooth/encrypting-ballot-screen-directive/encrypting-ballot-screen-directive.html
- avBooth/encrypting-ballot-screen-directive/encrypting-ballot-screen-directive.js
- avBooth/invalid-answers-controller/invalid-answers-controller.html
- avBooth/multi-question-directive/multi-question-directive.html
- avBooth/pairwise-beta-directive/pairwise-beta-directive.html
- avBooth/pcandidates-election-screen-directive/pcandidates-election-screen-directive.html
- avBooth/review-ballot-directive/review-ballot-directive.html
- avBooth/review-ballot-directive/review-ballot-directive.js
- avBooth/review-ballot-directive/review-ballot-directive.less
- avBooth/simultaneous-question-answer-directive/simultaneous-question-answer-directive.html
- avBooth/simultaneous-question-answer-directive/simultaneous-question-answer-directive.less
- avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.html
- avBooth/success-screen-directive/success-screen-directive.html
- locales/en.json
- locales/es.json
* Don't logout after 10 mins on demo/live.
* Show a warning modal before the session expires.
* Fix alt text for logo.
* Fix contrast for text warning javascript is off.
* Fix skipped headers on election chooser.
* Improve accessibility on encrypting screen, aria hide changing images, set better description for header.
* Set tabindex to 0 (instead of > 0) on modals' buttons.
* Don't use a header on review ballot when it just contains an aria-hidden icon.
* Add a description for the edit action on review ballot.
* Add alert role to warnings on simultaneous questions screen.
* Better labels for checks (normal, invalid, write-in) on simultaneous questions screen.
* Disable tab for answer container on simultaneous questions screen. Users should only be able to use tab to go through …
>  Fix accessibility issues

- avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.js
- locales/en.json
- locales/es.json
* wip
* wip
* wip
* translations
> Add support for warn-invalid-implicit-and-explicit  (#298)

- avBooth/booth-directive/booth-directive.less
* Remove`linear-gradient` background for class `wrapper-unfixed:after`, which was creating problems. This class is used in almost every screen in the voting booth.
> Remove linear gradient

- avBooth/2questions-conditional-screen-directive/2questions-conditional-screen-directive.html
- avBooth/audit-ballot-screen-directive/audit-ballot-screen-directive.html
- avBooth/conditional-accordion-screen-directive/conditional-accordion-screen-directive.html
- avBooth/help-screen-directive/help-screen-directive.html
- avBooth/pairwise-beta-directive/pairwise-beta-directive.html
- avBooth/review-screen-directive/review-screen-directive.html
- avBooth/show-pdf-directive/show-pdf-directive.html
- avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.html
- avBooth/start-screen-directive/start-screen-directive.html
* In all screens using the affix bottom directive, force it to be active if the election config `election.presentation.anchor_continue_btn_to_bottom`is set to true.
> Always fix continue button to bottom

- .github/workflows/ort.yml
Use the reusable workflow from the meta repository instead.
> Fix ORT Github Workflow (#317)

- avBooth/review-screen-directive/review-screen-directive.html
- avBooth/review-screen-directive/review-screen-directive.less
- avBooth/simultaneous-questions-screen-directive/simultaneous-questions-screen-directive.js
Parent issue: https://github.com/sequentech/epi/issues/111
When a ballot is invalid implicitly (for example by selecting too many choices by the voter), the voting screen shows a warning to the voter telling him that this will make the ballot invalid However, in the review screen no warning is shown. The proposal is to show this warning in the review screen too.
Note that this feature is already implemented for the [new voting booth design](https://github.com/sequentech/voting-booth/issues/304) that will be launched in a couple weeks in version `8.0.0`, but EPI wants to have access to this feature in version `7.x` to be able to deploy the breaking changes of version `8.0.0` later with more time and internal testing.
After a debate seen below, we implemented this feature by saving the …
> Voting Booth: show ballot warnings in review screen (#322)

- package.json
- yarn.lock
Parent issue: https://github.com/sequentech/meta/issues/75
Fixes https://github.com/sequentech/voting-booth/security/dependabot/26
> Bump engine.io from 6.1.0 to 6.4.2 (#324)

- package.json
- yarn.lock
Parent issue: https://github.com/sequentech/meta/issues/83
Related dependabot alert:
https://github.com/sequentech/voting-booth/security/dependabot/28
> Bump socket.io-parser from 4.0.4 to 4.2.3 (#328)

- SequentConfig.js
- avBooth/booth-directive/booth-directive.js
- locales/ca.json
- locales/en.json
- locales/es.json
- locales/fi.json
- locales/fr.json
- locales/gl.json
- locales/sv.json
Parent issue: https://github.com/sequentech/epi/issues/19
> ✨ Countdown until logout

- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.less
Problem solved: checkboxes overflow to the side instead of wrapping in a new rows.
> Fix: Responsive wraps for high cumulative votes

- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.less
Problem solved: checkboxes overflow to the side instead of wrapping in a new rows.
> Fix: Responsive wraps for high cumulative votes (#367)

- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.html
- avBooth/simultaneous-question-answer-v2-directive/simultaneous-question-answer-v2-directive.less
Problem solved: checkboxes overflow to the side instead of wrapping in a new rows. Previous fix was incomplete.
> Fix: Responsive wraps for high cumulative votes (#371)

- app.js
- avBooth/booth-directive/booth-directive.js
- avBooth/booth.html
- avBooth/booth.js
Parent issue: https://github.com/sequentech/meta/issues/752
> ✨🐞 Improve/rethink/fix Live Preview (#450)

- avBooth/booth-directive/booth-directive.js
Parent issue: https://github.com/sequentech/meta/issues/205
> ✨ Increase the timeout due to user activity (#451)

- app.js
- app.less
- avBooth/booth-children-elections-directive/booth-children-elections-directive.html
- avBooth/booth-children-elections-directive/booth-children-elections-directive.js
- avBooth/booth-directive/booth-directive.html
- avBooth/booth-directive/booth-directive.js
- avBooth/booth.html
- avBooth/booth.js
- avBooth/election-chooser-screen-directive/election-chooser-screen-directive.js
- avBooth/voter-eligibility-screen-directive/voter-eligibility-screen-directive.html
- avBooth/voter-eligibility-screen-directive/voter-eligibility-screen-directive.js
- avBooth/voter-eligibility-screen-directive/voter-eligibility-screen-directive.less
- index.html
Parent issue: https://github.com/sequentech/meta/issues/234
> ✨ Voter eligibility check (#454)

- avBooth/booth-directive/booth-directive.js
Parent issue: https://github.com/sequentech/meta/issues/1832
> 🐞 Login error for voters (#468) (#469)
